name: Create PR for each CE commit from Enterprise to OSS

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  create-prs-for-ce-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OSS repo
        uses: actions/checkout@v2
        with:
          repository: karthik-sivadas/multiwoven
          ref: main

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add enterprise remote
        run: |
          git remote add enterprise git@github.com:Multiwoven/multiwoven-ee.git
          git fetch enterprise

      - name: Get date five days ago
        id: date-five-days-ago
        run: |
          FIVE_DAYS_AGO=$(date -d "5 days ago" +'%Y-%m-%d')
          echo "::set-output name=date::$FIVE_DAYS_AGO"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create PRs for each CE commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git log enterprise/main  --since="5 days ago" --format="%H" | while read sha; do
            echo "Processing commit: $sha"
            AUTHOR_NAME=$(git log -1 --pretty=format:'%an' $sha)
            AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae' $sha)
            COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s' $sha)
            BRANCH_NAME="cherry-pick-ce-commit-${sha}"
            git checkout -b $BRANCH_NAME
            git cherry-pick $sha || {
              echo "Conflict in commit $sha, resolving manually."
              git add .
              git commit -am "Resolve conflict in cherry-pick of $sha and change the commit message"
            }
            git push --force --set-upstream origin $BRANCH_NAME
            PR_TITLE="${COMMIT_MESSAGE}"
            PR_BODY="This PR cherry-picks the CE commit ${commit} from the Enterprise repository. Commit author: ${AUTHOR_NAME} (${AUTHOR_EMAIL})"
            AUTHOR_GH_USERNAME=$(gh api graphql -f query='query { search(query: "${AUTHOR_EMAIL}", type: USER, first: 1) { nodes { ... on User { login } } } }' -q '.data.search.nodes[0].login')
            if [ -n "$AUTHOR_GH_USERNAME" ]; then
              PR_BODY="${PR_BODY}\n\ncc @${AUTHOR_GH_USERNAME}"
              gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME --assignee "$AUTHOR_GH_USERNAME"
            else
              gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME
            fi
            git checkout main
            git branch -D $BRANCH_NAME
          done
